name: OsirisBETA

on: [pull_request, push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild SSE2
      working-directory: Osiris
      run: msbuild Osiris.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m /p:OutDir="D:\a\Osiris\Osiris\Osiris\Release\SSE2\"
    - name: Rename SSE2
      working-directory: Osiris/Release/SSE2
      run: ren Osiris.dll Osiris_BETA_SSE2.dll
      shell: cmd
    - name: Move to one folder SSE2
      working-directory: Osiris
      run: |
            mkdir D:\a\Osiris\Osiris\Osiris\ready
            Copy-Item -Path D:\a\Osiris\Osiris\Osiris\Release\SSE2\Osiris_BETA_SSE2.dll -Destination D:\a\Osiris\Osiris\Osiris\ready\
            Remove-Item -LiteralPath "Release" -Force -Recurse
    - name: SHA1 SSE2
      working-directory: Osiris/ready
      run: sha1sum Osiris_BETA_SSE2.dll > Osiris_BETA_SSE2.dll.sha1
      
    - name: Rename AVX
      working-directory: Osiris
      run: 
          |
          ren Osiris.vcxproj Osiris_AVX.vcxproj
          ren Osiris.vcxproj.filters Osiris_AVX.vcxproj.filters
      shell: cmd
    - name: Prepare AVX
      working-directory: Osiris
      run: |
            ((Get-Content Osiris_AVX.vcxproj -Raw) -replace '<EnableEnhancedInstructionSet>StreamingSIMDExtensions2</EnableEnhancedInstructionSet>','<EnableEnhancedInstructionSet>AdvancedVectorExtensions</EnableEnhancedInstructionSet>') | Set-Content Osiris_AVX.vcxproj
      shell: pwsh
    - name: MSBuild AVX
      working-directory: Osiris
      run: msbuild Osiris_AVX.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m /p:OutDir="D:\a\Osiris\Osiris\Osiris\Release\AVX\"
    - name: Rename AVX
      working-directory: Osiris/Release/AVX
      run: ren Osiris_AVX.dll Osiris_BETA_AVX.dll
      shell: cmd
    - name: Move to one folder AVX
      working-directory: Osiris
      run: |
            Copy-Item -Path D:\a\Osiris\Osiris\Osiris\Release\AVX\Osiris_BETA_AVX.dll -Destination D:\a\Osiris\Osiris\Osiris\ready\
            Remove-Item -LiteralPath "Release" -Force -Recurse
    - name: SHA1 AVX
      working-directory: Osiris/ready
      run: sha1sum Osiris_BETA_AVX.dll > Osiris_BETA_AVX.dll.sha1
      
    - name: Rename AVX2
      working-directory: Osiris
      run: 
          |
          ren Osiris_AVX.vcxproj Osiris_AVX2.vcxproj
          ren Osiris_AVX.vcxproj.filters Osiris_AVX2.vcxproj.filters
      shell: cmd
    - name: Prepare AVX2
      working-directory: Osiris
      run: |
            ((Get-Content Osiris_AVX2.vcxproj -Raw) -replace '<EnableEnhancedInstructionSet>AdvancedVectorExtensions</EnableEnhancedInstructionSet>','<EnableEnhancedInstructionSet>AdvancedVectorExtensions2</EnableEnhancedInstructionSet>') | Set-Content Osiris_AVX2.vcxproj
      shell: pwsh
    - name: MSBuild AVX2
      working-directory: Osiris
      run: msbuild Osiris_AVX2.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m /p:OutDir="D:\a\Osiris\Osiris\Osiris\Release\AVX2\"
    - name: Rename AVX2
      working-directory: Osiris/Release/AVX2
      run: ren Osiris_AVX2.dll Osiris_BETA_AVX2.dll
      shell: cmd
    - name: Move to one folder AVX2
      working-directory: Osiris
      run: |
            Copy-Item -Path D:\a\Osiris\Osiris\Osiris\Release\AVX2\Osiris_BETA_AVX2.dll -Destination D:\a\Osiris\Osiris\Osiris\ready\
            Remove-Item -LiteralPath "Release" -Force -Recurse
    - name: SHA1 AVX2
      working-directory: Osiris/ready
      run: sha1sum Osiris_BETA_AVX2.dll > Osiris_BETA_AVX2.dll.sha1
      
    - name: Get Injector
      run: |
            git clone https://github.com/playday3008/Osiris-GOESP-inj.git
            cd .\Osiris-GOESP-inj\src
            & '.\__asm_emit generator.exe' (Get-Random -Minimum 300 -Maximum 500) 1
            Remove-Item -Path Osiris-inj\JunkDef.h
            Move-Item -Path junk.h -Destination Osiris-inj\JunkDef.h
            cd .\Osiris-inj
            ((Get-Content Main.cpp -Raw) -replace '//#define BETA','#define BETA') | Set-Content Main.cpp
            msbuild Osiris-inj.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m
            Copy-Item -Path D:\a\Osiris\Osiris\Osiris-GOESP-inj\src\Osiris-inj\Release\Osiris-inj.exe -Destination "D:\a\Osiris\Osiris\Osiris\ready\Osiris-Injector.exe"
      shell: pwsh
      
    - name: Open CFG folder (BAT)
      run: |
            Add-Content -path "D:\a\Osiris\Osiris\Osiris\ready\Open CFG folder (Открыть папку с КФГ).bat" -value "@echo off`r`necho `"Wait a second`"`r`nIF EXIST %USERPROFILE%\Documents\Osiris (`r`n%SystemRoot%\explorer.exe `"%USERPROFILE%\Documents\Osiris`"`r`n) ELSE (`r`nmkdir %USERPROFILE%\Documents\Osiris`r`n%SystemRoot%\explorer.exe `"%USERPROFILE%\Documents\Osiris`"`r`n)`r`nstart `"`" https://youtu.be/xY3oX_cpAVs"
      shell: pwsh
      
    - uses: actions/upload-artifact@v1
      with:
        name: Osiris Beta All
        path: Osiris/ready
