name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.continue-on-error }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        compiler: [g++-10, g++-11, g++-12, clang++-12, clang++-13, clang++-14]
        configuration: [Debug, Release]
        exclude:
          - os: ubuntu-20.04
            compiler: g++-12
          - os: ubuntu-20.04
            compiler: clang++-13
          - os: ubuntu-20.04
            compiler: clang++-14
        include:
          - os: ubuntu-22.04
            continue-on-error: true
          - os: ubuntu-20.04
            continue-on-error: false
    steps:
    - uses: actions/checkout@v2
    - name: Add toolchain PPA
      if: matrix.compiler == 'g++-11'
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - name: install
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libfreetype-dev ${{ matrix.compiler }}
    - name: configure
      run: cmake -D CMAKE_BUILD_TYPE=${{ matrix.configuration }} -D CMAKE_CXX_COMPILER=${{ matrix.compiler }} -D BUILD_TESTS=1 -S . -B ${{ matrix.configuration }}
    - name: build
      run: cmake --build ${{ matrix.configuration }} -j $(nproc --all)
    - name: run unit tests
      run: |
        cd ${{ matrix.configuration }}
        ctest --output-on-failure --schedule-random -j $(nproc --all)
