name: Linux

on: [push, pull_request]

jobs:
  gcc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev gcc-10 g++-10
    - name: configure
      run: mkdir Release && cd Release && cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 ..
    - name: build
      run: cd Release && make -j $(nproc --all)
      
  clang:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev clang-10
    - name: configure
      run: mkdir Release && cd Release && cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=clang-10 -D CMAKE_CXX_COMPILER=clang++-10 ..
    - name: build
      run: cd Release && make -j $(nproc --all)
